#!/bin/bash

#echo "Content-type: text/html;charset=UTF-8"
#echo

if [ -z "$CONFIG_WMS_IMAGEWIDTH" ]
then
 SHELLGET_INTEGER_MAPIMAGEWIDTH=$(shell_get_value "mapimagewidth")
 SHELLGET_INTEGER_MAPIMAGEWIDTH=$(check_value_integerbetweendefault "$SHELLGET_INTEGER_MAPIMAGEWIDTH" "0" "$SHELLGET_INTEGER_MAPIMAGEWIDTH" "$CONFIG_WMS_IMAGEMAXWIDTH")

 CONFIG_WMS_CALCULATEDWIDTH=$(( ($CONFIG_WMS_DEFAULTHEIGHT / $CONFIG_WMS_IMAGEHEIGHT) * $SHELLGET_INTEGER_MAPIMAGEWIDTH ))
 CONFIG_WMS_DEFAULTRELATIVEX=$(( ($CONFIG_WMS_DEFAULTWIDTH - $CONFIG_WMS_CALCULATEDWIDTH) / 2 ))
 CONFIG_WMS_DEFAULTWIDTH=$CONFIG_WMS_CALCULATEDWIDTH
else
 SHELLGET_INTEGER_MAPIMAGEWIDTH="$CONFIG_WMS_IMAGEWIDTH"
fi

SHELLGET_INTEGER_LEFTX=$(shell_get_value "leftx")
SHELLGET_INTEGER_TOPY=$(shell_get_value "topy")
SHELLGET_INTEGER_ZOOMLEVEL=$(shell_get_value "zoomlevel")

GLOBAL_BOOLEAN_CORRECTBBOX=$(check_value_integerbetween "$SHELLGET_INTEGER_ZOOMLEVEL" "$CONFIG_WMS_ZOOMLEVELMINIMUM" "$CONFIG_WMS_ZOOMLEVELMAXIMUM")

if [ "$GLOBAL_BOOLEAN_CORRECTBBOX" = false ]
then
 # Calculate maximumx

 GLOBAL_BOOLEAN_CORRECTBBOX=$(check_value_integerbetween "$SHELLGET_INTEGER_LEFTX" "$CONFIG_WMS_MINIMUMX" "$CONFIG_WMS_MAXIMUMX")
fi

if [ "$GLOBAL_BOOLEAN_CORRECTBBOX" = false ]
then
 # Calculate maximumy

 GLOBAL_BOOLEAN_CORRECTBBOX=$(check_value_integerbetween "$SHELLGET_INTEGER_TOPY" "$CONFIG_WMS_MINIMUMY" "$CONFIG_WMS_MAXIMUMY")
fi

if [ "$GLOBAL_BOOLEAN_CORRECTBBOX" = true ]
then
 SHELLGET_INTEGER_LEFTX="$CONFIG_WMS_DEFAULTLEFTX"
 SHELLGET_INTEGER_TOPY="$CONFIG_WMS_DEFAULTTOPY"
 SHELLGET_INTEGER_ZOOMLEVEL="$CONFIG_WMS_DEFAULTZOOMLEVEL"
fi

#echo "---$SHELLGET_INTEGER_ZOOMLEVEL" "$SHELLGET_INTEGER_LEFTX" "$SHELLGET_INTEGER_TOPY---"
GLOBAL_BBOX_MAPIMAGE=$(calculate_bbox "$SHELLGET_INTEGER_ZOOMLEVEL" "$SHELLGET_INTEGER_LEFTX" "$SHELLGET_INTEGER_TOPY")
#echo "===$SHELLGET_INTEGER_MAPIMAGEWIDTH" "$GLOBAL_BBOX_MAPIMAGE==="

request_image_wms "$SHELLGET_INTEGER_MAPIMAGEWIDTH" "$GLOBAL_BBOX_MAPIMAGE"
